# Generated by Django 4.1.7 on 2023-05-07 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0011_alter_userdata_certificate_alter_userdata_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCache',
            fields=[
                ('link', models.CharField(default='unknown', max_length=200, primary_key=True, serialize=False)),
                ('content', models.CharField(default='', max_length=300)),
                ('img', models.CharField(default='', max_length=200)),
                ('isFake', models.BooleanField(default=False)),
            ],
        ),
    ]
