# Generated by Django 4.1.7 on 2023-05-07 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_alter_userdata_certificate_alter_userdata_pic'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionApproves',
            fields=[
                ('link', models.CharField(default='unknown', max_length=200, primary_key=True, serialize=False)),
                ('approved', models.BooleanField(default=True)),
                ('expertId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.userdata')),
            ],
        ),
    ]
