# Generated by Django 4.1.7 on 2023-05-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_predictionapproves'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredictionApproves',
        ),
    ]
