# Generated by Django 4.1.7 on 2023-05-07 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_alter_userdata_certificate_alter_userdata_pic'),
        ('articles', '0003_delete_predictionapproves'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionApproves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='unknown', max_length=200)),
                ('approved', models.BooleanField(default=True)),
                ('expertId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.userdata')),
            ],
        ),
    ]
