# Generated by Django 4.1.7 on 2023-05-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_alter_userdata_certificate_alter_userdata_pic'),
        ('articles', '0005_alter_predictionapproves_expertid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionapproves',
            name='expertId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.userdata'),
        ),
    ]
