# Generated by Django 4.1.7 on 2023-05-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_predictionapproves_expertid'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionapproves',
            name='expertName',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='predictionapproves',
            name='expertId',
            field=models.IntegerField(),
        ),
    ]
