# Generated by Django 4.1.7 on 2023-05-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_predictionapproves_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionapproves',
            name='title',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
