# Generated by Django 4.1.7 on 2023-04-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='ProfilePicture',
            field=models.ImageField(null=True, upload_to='media/uploads'),
        ),
    ]
