# Generated by Django 4.1.7 on 2023-04-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_userdata_profilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='ProfilePicture',
        ),
    ]
