# Generated by Django 4.1.7 on 2023-04-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_userdata_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='pic',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
