# Generated by Django 4.1.7 on 2023-04-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_userdata_isexpert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Certificate',
            field=models.ImageField(null=True, upload_to='media/Certificates/'),
        ),
    ]
