# Generated by Django 4.1.7 on 2023-04-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_userdata_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='gender',
        ),
        migrations.AddField(
            model_name='userdata',
            name='lastname',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
    ]
