# Generated by Django 4.1.7 on 2023-04-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_remove_userdata_age_remove_userdata_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='Pending',
            field=models.BooleanField(default=False),
        ),
    ]
