# Generated by Django 4.1.7 on 2023-04-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=100)),
                ('email', models.CharField(default='unknown', max_length=40)),
                ('title', models.CharField(default='', max_length=40)),
                ('content', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
